### ISSUE TITLE
 "error_description": "Client id mismatch in credentials for this pin grant",

### ISSUE THREAD

**Issue by stickerx** [xMistt/DeviceAuthGenerator#4] opened 2021-09-09 23:07 UTC
![2021-09-09_230612](https://user-images.githubusercontent.com/41187653/132773968-a5b3dac5-a3af-4031-bba6-31365d0a9056.jpg)

**Comment by vsxd** [comment] 2021-09-10 07:00
I have the same problem

```
DeviceAuthGenerator v1.1.0 made by xMistt // Oli. Ask for help in PartyBot.
sh: cls: command not found
Opening device code link in a new tab.
sh: cls: command not found
Waiting for completion.
{
    "errorCode": "errors.com.epicgames.common.oauth.invalid_token",
    "errorMessage": "Client id mismatch in credentials for this pin grant",
    "messageVars": [],
    "numericErrorCode": 1012,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Client id mismatch in credentials for this pin grant",
    "error": "invalid_grant"
}

```

**Comment by insoxin** [comment] 2021-09-10 08:02
Client id mismatch in credentials for this pin grant

**Comment by stickerx** [comment] 2021-09-12 19:12
Epic removed Arkos Labs and now only use HCaptcha.

Need to find a way to do the same stuff in the users browser instead of a selenium window.

**Comment by 9520fun** [comment] 2021-09-13 11:31
But how can we do that

**Comment by Dr-Shiki** [comment] 2021-09-17 08:37
just nothing we could do right now?

**Comment by jackblk** [comment] 2021-09-21 20:17
This issue is duplicated with #3 

I fixed it on my fork, you can check it in this comment: https://github.com/xMistt/DeviceAuthGenerator/issues/3#issuecomment-924350309

**Comment by Tweetpine** [comment] 2021-11-05 11:04
Hi i still have the problem 

Please help 

![Device-error](https://user-images.githubusercontent.com/30963156/140500988-5879a59f-a16c-458f-93da-8ded3d580f34.png)

**Comment by Nugget2269** [comment] 2021-11-16 19:45
@Tweetpine you have to compile it yourself to get the newest update.

**Comment by Tweetpine** [comment] 2021-11-16 21:22
@Marethyu9999 Thank you 

It works now!

**Comment by JohanSF** [comment] 2021-11-18 06:50
Still doesn't work for me, using the executable from the Releases section.

**Comment by jackblk** [comment] 2021-11-18 06:51
> Still doesn't work for me, using the executable from the Releases section.

Try my fork, I fixed it a while ago https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1

**Comment by JohanSF** [comment] 2021-11-18 06:54
Thank you, it works!

**Comment by xMistt** [comment] 2022-03-19 13:18
Duplicate of https://github.com/xMistt/DeviceAuthGenerator/issues/3.

**Closed as completed by xMistt** 2022-03-19 13:18 UTC
