### ISSUE TITLE
invalid grant

### ISSUE THREAD

**Issue by Jennal** [xMistt/DeviceAuthGenerator#11] opened 2021-11-19 09:35 UTC
```
{
    "errorCode": "errors.com.epicgames.common.oauth.invalid_token",
    "errorMessage": "Client id mismatch in credentials for this pin grant",
    "messageVars": [],
    "numericErrorCode": 1012,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Client id mismatch in credentials for this pin grant",
    "error": "invalid_grant"
}
```

**Comment by ZombiePm** [comment] 2021-11-19 15:23
+

**Comment by jackblk** [comment] 2021-11-19 15:38
Dup of #3 

You can try the patched version here: https://github.com/xMistt/DeviceAuthGenerator/issues/3#issuecomment-924350309

**Comment by ZombiePm** [comment] 2021-11-19 16:15
[https://github.com/jackblk/DeviceAuthGenerator](url) Working fork/ Thannks

**Comment by xMistt** [comment] 2022-03-19 13:16
Do you still experience this? It's working fine for me.

**Comment by xMistt** [comment] 2022-03-19 13:18
Duplicate of https://github.com/xMistt/DeviceAuthGenerator/issues/3.

**Closed as completed by xMistt** 2022-03-19 13:18 UTC
